version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
    - $PWD/docker-volumes/mongo-data:/data/db
    - $PWD/docker-volumes/mongo-config:/data/configdb
    ports:
      - 27017:27017

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
     - $PWD/docker-volumes/redis-data:/var/lib/redis
     - $PWD/docker-volumes/redis.conf:/usr/local/etc/redis/redis.conf
